import jsPDF from 'jspdf'
import 'jspdf-autotable'
import { formatINR } from './utils'

/**
 * Generate a monthly financial summary PDF.
 * @param {object} state - full app state
 * @param {string} monthYear - e.g. '2026-04'
 * @param {string} userName - user's display name
 */
export function generateMonthlyReport(state, monthYear, userName) {
  const doc = new jsPDF()
  const [year, month] = monthYear.split('-')
  const monthName = new Date(year, month - 1).toLocaleString('en-IN', { month: 'long', year: 'numeric' })

  // Filter transactions for this month
  const txs = (state.transactions || []).filter(t => t.date.startsWith(monthYear))
  const income = txs.filter(t => t.type === 'income').reduce((s, t) => s + t.amount, 0)
  const expenses = txs.filter(t => t.type === 'expense').reduce((s, t) => s + t.amount, 0)
  const transfers = txs.filter(t => t.type === 'transfer').reduce((s, t) => s + t.amount, 0)
  const savings = income - expenses
  const savingsRate = income > 0 ? ((savings / income) * 100).toFixed(1) : '0'

  // Category breakdown
  const catSpend = {}
  txs.filter(t => t.type === 'expense').forEach(t => {
    const cat = (state.categories || []).find(c => c.id === t.categoryId)
    const name = cat?.name || 'Other'
    catSpend[name] = (catSpend[name] || 0) + t.amount
  })
  const catData = Object.entries(catSpend).sort((a, b) => b[1] - a[1])

  // Header
  doc.setFillColor(24, 15, 50)
  doc.rect(0, 0, 210, 40, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(22)
  doc.text('ExpenseFlow', 15, 18)
  doc.setFontSize(11)
  doc.setTextColor(180, 160, 220)
  doc.text(`Monthly Financial Report — ${monthName}`, 15, 28)
  if (userName) {
    doc.setFontSize(9)
    doc.text(`Prepared for: ${userName}`, 15, 35)
  }

  let y = 52

  // Summary section
  doc.setTextColor(60, 60, 60)
  doc.setFontSize(14)
  doc.text('Summary', 15, y)
  y += 8

  doc.autoTable({
    startY: y,
    head: [['Metric', 'Amount']],
    body: [
      ['Total Income', formatINR(income)],
      ['Total Expenses', formatINR(expenses)],
      ['Transfers / Investments', formatINR(transfers)],
      ['Net Savings', formatINR(savings)],
      ['Savings Rate', `${savingsRate}%`],
    ],
    theme: 'grid',
    headStyles: { fillColor: [124, 58, 237], textColor: 255 },
    styles: { fontSize: 10, cellPadding: 4 },
    margin: { left: 15, right: 15 },
  })

  y = doc.lastAutoTable.finalY + 14

  // Category breakdown
  if (catData.length > 0) {
    doc.setFontSize(14)
    doc.text('Spending by Category', 15, y)
    y += 8

    doc.autoTable({
      startY: y,
      head: [['Category', 'Amount', '% of Total']],
      body: catData.map(([name, amount]) => [
        name,
        formatINR(amount),
        `${((amount / expenses) * 100).toFixed(1)}%`
      ]),
      theme: 'grid',
      headStyles: { fillColor: [124, 58, 237], textColor: 255 },
      styles: { fontSize: 10, cellPadding: 4 },
      margin: { left: 15, right: 15 },
    })

    y = doc.lastAutoTable.finalY + 14
  }

  // Top 10 transactions
  const topTx = txs
    .filter(t => t.type === 'expense')
    .sort((a, b) => b.amount - a.amount)
    .slice(0, 10)

  if (topTx.length > 0) {
    if (y > 230) { doc.addPage(); y = 20 }

    doc.setFontSize(14)
    doc.text('Top 10 Expenses', 15, y)
    y += 8

    doc.autoTable({
      startY: y,
      head: [['Date', 'Description', 'Category', 'Amount']],
      body: topTx.map(t => {
        const cat = (state.categories || []).find(c => c.id === t.categoryId)
        return [
          t.date,
          t.description,
          cat?.name || 'Other',
          formatINR(t.amount),
        ]
      }),
      theme: 'grid',
      headStyles: { fillColor: [124, 58, 237], textColor: 255 },
      styles: { fontSize: 9, cellPadding: 3 },
      margin: { left: 15, right: 15 },
    })

    y = doc.lastAutoTable.finalY + 14
  }

  // Account balances
  const accounts = state.accounts || []
  if (accounts.length > 0) {
    if (y > 240) { doc.addPage(); y = 20 }

    doc.setFontSize(14)
    doc.text('Account Balances', 15, y)
    y += 8

    doc.autoTable({
      startY: y,
      head: [['Account', 'Bank', 'Type', 'Balance']],
      body: accounts.map(a => [a.name, a.bank, a.type, formatINR(a.balance)]),
      theme: 'grid',
      headStyles: { fillColor: [124, 58, 237], textColor: 255 },
      styles: { fontSize: 10, cellPadding: 3 },
      margin: { left: 15, right: 15 },
    })
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(`Generated by ExpenseFlow · Page ${i} of ${pageCount}`, 105, 290, { align: 'center' })
  }

  // Download
  doc.save(`ExpenseFlow-Report-${monthYear}.pdf`)
}
